services:
  - type: web
    name: smart-healthcare-backend
    env: python
    rootDirectory: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: 3.11.9
