services:
  - type: web
    name: smart-healthcare-chatbot-internship-project
    runtime: python
    repo: https://github.com/adarshgogate/smart-healthcare-chatbot-internship-project
    plan: free
    envVars:
      - key: SQLALCHEMY_DATABASE_URI
        sync: false
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeployTrigger: commit
    rootDir: backend/
    pythonVersion: 3.11.9
